// @ts-nocheck
// This file is auto-generated by TanStack Router CLI during build.
// For development, this stub is sufficient for TypeScript to proceed.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRoute } from "./routes/index";

const routeTree = rootRoute.addChildren([IndexRoute]);
export { routeTree };
